version: 2.1

commands:
  save-git-cache:
    steps:
      - save_cache:
          key: git-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git/
  load-git-cache:
    steps:
      - restore_cache:
          keys:
            - git-v1-{{ .Branch }}-{{ .Revision }}
            - git-v1-{{ .Branch }}
            - git-v1-
  save-m2-cache:
    steps:
      - save_cache:
          key: m2-v1-{{ .Branch }}-{{ checksum "pom.xml" }}-{{ .Revision }}
          paths:
            - ~/.m2/
  load-m2-cache:
    steps:
      - restore_cache:
          keys:
            - m2-v1-{{ .Branch }}-{{ checksum "pom.xml" }}-{{ .Revision }}
            - m2-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - m2-v1-{{ .Branch }}
            - m2-v1-

executors:
  openjdk-executor:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/workdir/
    environment:
      TZ: Asia/Tokyo

jobs:
  install:
    executor: openjdk-executor
    steps:
      - load-git-cache
      - checkout
      - save-git-cache

      - load-m2-cache
      - run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run: mvn test -B
      - save-m2-cache

workflows:
  version: 2
  build:
    jobs:
      - install
