name: ${project.name}
main: net.azisaba.lgw.core.LeonGunWar
version: ${project.version}
authors: ["siloneco", "YukiLeafX"]
description: ${project.description}
website: ${project.url}
softdepend: ["Multiverse-Core", "CrackShot"]
commands:
  leongunwaradmin:
    description: Nothing
    permission: leongunwar.command.leongunwar
    aliases: ["lgwadmin"]
  uav:
    usage: /uav [Player]
    description: Nothing
    permission: leongunwar.command.uav
permissions:
  leongunwar.entrysign.changestate:
    default: op
  leongunwar.command.leongunwar:
    default: op
  leongunwar.afkkick.exempt:
    default: op
  leongunwar.command.uav:
    default: op