name: ${project.name}
main: net.azisaba.lgw.core.LeonGunWar
version: ${project.version}
authors: ["siloneco", "YukiLeafX"]
description: ${project.description}
website: ${project.url}
depend: ["CrackShot", "Essentials", "WorldGuard", "PlayerSettings", "KDStatusReloaded"]
softdepend: ["Multiverse-Core"]
commands:
  leongunwaradmin:
    description: Nothing
    permission: leongunwar.command.leongunwaradmin
    aliases: ["lgwadmin"]
  uav:
    usage: /uav [Player]
    description: Nothing
    permission: leongunwar.command.uav
  #match:
  #  usage: /match <entry/rejoin/leave> (player)
  #  permission: leongunwar.command.match
  mapvote:
    usage: /mapvote <index>
    permission: leongunwar.command.mapvote
    aliases: ["votemap"]
  kiai:
    usage: /kiai
    permission: leongunwar.command.kiai
  resourcepack:
    usage: /resourcepack
    aliases: ["pack", "texture"]
    permission: leongunwar.command.resourcepack
  adminchat:
    usage: /adminchat <msg>
    aliases: ["c"]
    permission: leongunwar.adminchat.send
  limit:
    usage: /limit [drop/build]
    permission: leongunwar.command.limit
permissions:
  leongunwar.entrysign.changestate:
    default: op
  leongunwar.command.leongunwaradmin:
    default: op
  leongunwar.afkkick.exempt:
    default: op
  leongunwar.command.uav:
    default: op
  #leongunwar.command.match:
  #  default: true
  leongunwar.command.mapvote:
    default: true
  leongunwar.command.match.other:
    default: op
  leongunwar.command.kiai:
    default: true
  leongunwar.command.resourcepack:
    default: true
  leongunwar.adminchat.send:
    default: op
  leongunwar.adminchat.receive:
    default: op
  leongunwar.command.limit:
    default: op
