name: Build Test
on:
  push:
    paths-ignore:
      - "**.md"
      - "renovate.json"
  pull_request:
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build-test:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    name: Build with Java 8
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
          cache: "maven"

      - name: Check 1.12.2 NMS existence
        id: check_nms
        uses: andstor/file-existence-action@v2
        with:
          files: "/home/runner/.m2/repository/org/spigotmc/spigot/1.12.2-R0.1-SNAPSHOT/spigot-1.12.2-R0.1-SNAPSHOT.pom"
      - name: Download BuildTools
        if: steps.check_nms.outputs.files_exists == 'false'
        run: mkdir -p ./build/ && curl -L -o ./build/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Run BuildTools
        if: steps.check_nms.outputs.files_exists == 'false'
        run: cd build && java -jar BuildTools.jar --rev 1.12.2

      - name: Check CrackShot existence
        id: check_crackshot
        uses: andstor/file-existence-action@v2
        with:
          files: "/home/runner/.m2/repository/com/shampaggon/CrackShot/0.98.11/CrackShot-0.98.11.pom"
      - name: Download CrackShot v0.98.11
        if: steps.check_crackshot.outputs.files_exists == 'false'
        run: curl -L -o CrackShot.jar https://dev.bukkit.org/projects/crackshot/files/3151915/download
      - name: Install CrackShot into local mvn repo
        if: steps.check_crackshot.outputs.files_exists == 'false'
        run: mvn install:install-file -Dfile=./CrackShot.jar -DgroupId=com.shampaggon -DartifactId=CrackShot -Dversion=0.98.11 -Dpackaging=jar -DgeneratePom=true

      - run: java -version
      - run: mvn --version
      - run: mvn -B package
