name: Maven

on: [push]

jobs:
  build:
    name: Build with Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: java -version
      - run: mvn --version
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-build-
      - run: mvn -B package

  deploy:
    name: Deploy with Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: java -version
      - run: mvn --version
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-deploy-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-deploy-
      - run: mvn -B package

      - uses: actions/checkout@v2
        with:
          repository: AzisabaNetwork/mvn-repo
          path: mvn-repo
      - run: mvn -B -DaltDeploymentRepository=mvn-repo::default::file://mvn-repo deploy
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.MAVEN_REPO_KEY }}
      - run: git config --global url.'ssh://git@github.com/'.insteadOf 'https://github.com/'
      - run: git config --global user.email 'null@azisaba.net'
      - run: git config --global user.name "$GITHUB_ACTOR"
      - run: |
          git commit -a -m "Deploy @ $(date)"
          git push origin master
        working-directory: mvn-repo
